# Generated by Django 4.1.1 on 2022-10-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_driver_drivername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='deliveryStatus',
            field=models.CharField(choices=[('1', 'Creado'), ('2', 'Entregado')], max_length=200, verbose_name='Estado'),
        ),
    ]
